sonar.projectName=pr-project
sonar.projectKey=pr-project
sonar.branch.name=dev
sonar.sources=/var/lib/docker/volumes/jenkins-volume/_data/workspace/jenkins-sonar-test:/usr/src
sonar.issuesReport.console.enable=true
sonar.tests=src/test
sonar.language=java
sonar.java.source=17
sonar.java.binaries=./target
sonar.junit.reportPaths=./target
sonar.sourceEncoding=UTF-8
sonar.host.url=https://aa11-218-235-89-202.ngrok-free.app
sonar.login=credentials('sonar-pr-token')

sonar.projectName=sonar_project01
sonar.projectKey=sonar_project01
sonar.branch.name=main
sonar.sources=/var/lib/docker/volumes/jenkins-volume/_data/workspace/jenkins-sonar-test:/usr/src
sonar.issuesReport.console.enable=true
sonar.tests=src/test
sonar.language=java
sonar.java.source=17
sonar.java.binaries=./target
sonar.junit.reportPaths=./target
sonar.sourceEncoding=UTF-8
sonar.host.url=https://192.168.10.15:9000
sonar.login=credentials('sonar-token')




