sonar.host.url=https://aa11-218-235-89-202.ngrok-free.app
sonar.projectName=pr-project
sonar.projectKey=pr-project
sonar.pullrequest.key=${ghprbPullId}
sonar.pullrequest.base=${ghprbTargetBranch}
sonar.pullrequest.branch=${ghprbSourceBranch}
sonar.issuesReport.console.enable=true
sonar.sources=src/main
sonar.tests=src/test
sonar.language=java
sonar.java.binaries=./target
sonar.sourceEncoding=UTF-8
sonar.scm.provider=git
fetch = +refs/heads/*:refs/remotes/origin/

sonar.host.url=https://aa11-218-235-89-202.ngrok-free.app
sonar.projectName=sonar_project01
sonar.projectKey=sonar_project01
sonar.branch.name=main
sonar.sources=src/main
sonar.issuesReport.console.enable=true
sonar.tests=src/test
sonar.language=java
sonar.java.binaries=./target
sonar.sourceEncoding=UTF-8
sonar.login=sqp_4e320673152c940a6c1ddb98ee09204ff2fe8c56
sonar.scm.provider=git








