sonar.projectName=sonar_project01
sonar.projectKey=sonar_project01
sonar.sources=src/main
sonar.issuesReport.console.enable=true
sonar.tests=src/test
sonar.language=java
sonar.java.source=17
sonar.java.binaries=./target
sonar.sourceEncoding=UTF-8

sonar.projectName=pr-project
sonar.projectKey=pr-project
sonar.pullrequest.key=1
sonar.pullrequest.base=dev
sonar.pullrequest.branch=main
sonar.sources=src/main
sonar.issuesReport.console.enable=true
sonar.tests=src/test
sonar.language=java
sonar.java.source=17
sonar.java.binaries=./target
sonar.sourceEncoding=UTF-8







